
import React from 'react';
import { cn } from '../../lib/utils';
import {
  BarChartOutlined,
  DashboardOutlined,
  TeamOutlined,
  PartitionOutlined,
  ShoppingCartOutlined,
  SoundOutlined,
  MailOutlined,
  ShareAltOutlined,
  ThunderboltOutlined,
  TagsOutlined,
  DollarOutlined,
  QuestionCircleOutlined,
  SettingOutlined,
  ProjectOutlined,
  HistoryOutlined,
  DropboxOutlined,
  MessageOutlined,
  CommentOutlined,
  NodeIndexOutlined,
  StarOutlined,
  DownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  RightOutlined,
  LeftOutlined,
  MenuOutlined,
  SearchOutlined,
  SunOutlined,
  MoonOutlined,
  BellOutlined,
  UserOutlined,
  LogoutOutlined,
  PaperClipOutlined,
  DownloadOutlined,
  PlusOutlined,
  MoreOutlined,
  EditOutlined,
  PhoneOutlined,
  CalendarOutlined,
  AimOutlined,
  RiseOutlined,
  CheckCircleOutlined,
  WarningOutlined,
  CloseOutlined,
  FacebookFilled,
  InstagramFilled,
  TwitterOutlined,
  LinkedinFilled,
  YoutubeFilled,
  PinterestFilled,
  TikTokOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
  CreditCardOutlined,
  FileTextOutlined,
  ExperimentOutlined,
  BranchesOutlined,
  SelectOutlined,
  PercentageOutlined,
  WifiOutlined,
  CodeOutlined,
  MinusOutlined,
  ExpandOutlined,
  FontSizeOutlined,
  AlignLeftOutlined,
  AlignCenterOutlined,
  AlignRightOutlined,
  UserAddOutlined,
  UserDeleteOutlined,
  HeartOutlined,
  InfoCircleOutlined,
  CloseCircleOutlined,
  CheckOutlined,
  SyncOutlined,
  EyeOutlined,
  FormOutlined,
  CopyOutlined,
  InboxOutlined,
  DeleteOutlined,
  UploadOutlined,
  PlayCircleOutlined,
  PauseCircleOutlined,
  PictureOutlined,
  LayoutOutlined,
  AppstoreOutlined,
  BarsOutlined,
  GlobalOutlined,
  BookOutlined,
  LikeOutlined,
  SmileOutlined,
  EnvironmentOutlined,
  ClockCircleOutlined,
  WhatsAppOutlined
} from '@ant-design/icons';

interface IconProps extends React.HTMLAttributes<HTMLSpanElement> {
  name: string;
  className?: string;
}

const icons = {
  analytics: BarChartOutlined,
  dashboard: DashboardOutlined,
  users: TeamOutlined,
  segment: PartitionOutlined,
  shoppingCart: ShoppingCartOutlined,
  megaphone: SoundOutlined,
  mail: MailOutlined,
  share: ShareAltOutlined,
  zap: ThunderboltOutlined,
  ticket: TagsOutlined,
  dollarSign: DollarOutlined,
  lifeBuoy: QuestionCircleOutlined,
  settings: SettingOutlined,
  pipeline: ProjectOutlined,
  activity: HistoryOutlined,
  package: DropboxOutlined,
  messageSquare: MessageOutlined,
  messageCircle: CommentOutlined,
  workflow: NodeIndexOutlined,
  sparkles: StarOutlined,
  chevronDown: DownOutlined,
  arrowLeft: ArrowLeftOutlined,
  arrowRight: ArrowRightOutlined,
  chevronRight: RightOutlined,
  chevronLeft: LeftOutlined,
  menu: MenuOutlined,
  search: SearchOutlined,
  sun: SunOutlined,
  moon: MoonOutlined,
  bell: BellOutlined,
  user: UserOutlined,
  logout: LogoutOutlined,
  paperclip: PaperClipOutlined,
  download: DownloadOutlined,
  plus: PlusOutlined,
  moreVertical: MoreOutlined, // Needs rotation in render
  edit: EditOutlined,
  phone: PhoneOutlined,
  calendar: CalendarOutlined,
  target: AimOutlined,
  trendingUp: RiseOutlined,
  checkCircle: CheckCircleOutlined,
  alertTriangle: WarningOutlined,
  close: CloseOutlined,
  facebook: FacebookFilled,
  instagram: InstagramFilled,
  tiktok: TikTokOutlined,
  twitter: TwitterOutlined,
  arrowUp: ArrowUpOutlined,
  arrowDown: ArrowDownOutlined,
  creditCard: CreditCardOutlined,
  fileText: FileTextOutlined,
  beaker: ExperimentOutlined,
  'git-branch': BranchesOutlined,
  mousePointer: SelectOutlined,
  percent: PercentageOutlined,
  barChart: BarChartOutlined,
  wifi: WifiOutlined,
  battery: ThunderboltOutlined,
  code: CodeOutlined,
  minus: MinusOutlined,
  maximize: ExpandOutlined,
  type: FontSizeOutlined,
  'align-left': AlignLeftOutlined,
  'align-center': AlignCenterOutlined,
  'align-right': AlignRightOutlined,
  userPlus: UserAddOutlined,
  userMinus: UserDeleteOutlined,
  helpCircle: QuestionCircleOutlined,
  userX: UserDeleteOutlined,
  heart: HeartOutlined,
  box: DropboxOutlined,
  info: InfoCircleOutlined,
  xCircle: CloseCircleOutlined,
  check: CheckOutlined,
  refreshCw: SyncOutlined,
  eye: EyeOutlined,
  edit2: FormOutlined,
  linkedin: LinkedinFilled,
  youtube: YoutubeFilled,
  pinterest: PinterestFilled,
  copy: CopyOutlined,
  archive: InboxOutlined,
  trash: DeleteOutlined,
  upload: UploadOutlined,
  play: PlayCircleOutlined,
  pause: PauseCircleOutlined,
  image: PictureOutlined,
  layout: LayoutOutlined,
  grid: AppstoreOutlined,
  list: BarsOutlined,
  globe: GlobalOutlined,
  bookmark: BookOutlined,
  thumbsUp: LikeOutlined,
  smile: SmileOutlined,
  mapPin: EnvironmentOutlined,
  star: StarOutlined,
  clock: ClockCircleOutlined,
  whatsapp: WhatsAppOutlined
};

const Icon: React.FC<IconProps> & { icons: typeof icons } = ({ name, className, ...props }) => {
  const IconComponent = icons[name as keyof typeof icons];
  
  if (!IconComponent) {
    console.warn(`Icon "${name}" not found`);
    return null;
  }

  return (
    <span {...props} className={cn("inline-flex items-center justify-center", className)}>
        <IconComponent className={cn(
            "w-full h-full", 
            name === 'moreVertical' && "rotate-90"
        )} />
    </span>
  );
};

Icon.icons = icons;

export { Icon };
